---
title: "2017-07-18 Notebook"
output: html_notebook
---

Implementing data prep functions for bamr. I need the following:

- `bam_data`, to format W, S, dA. Produce bamdata object that bam_estimate will use. 
    - returns an object of class bamdata
    - Has plot() methods
- `bam_piors`, to set any priors I may want to change
    - returns an object of class bampriors
    - has plot() methods
- `bam_limits`, to set any parameter bounds I may want to change
    - returns an object of class bamlimits
    - I don't see how plotting would be useful, but print() should look nice.

I need to figure out how to store defaults. Possible ways are:

- Use an internal dataset, a list. 
    - pros: mutable, able to create multiple instances per session.
    - cons: unclear whether internal datasets are meant to be used this way.
- Use options(). 
    - pros: mutable, a common place to store default values needed by a package, easy for user to change defaults
    - cons: 
        - Can't have more than one set of values per session. Since these are just defaults, not necessarily important. 
        - May end up with an absurd number of options. 
      - **If I go this way:** use **settings** package (see vignette)
- Use reference class object
    - pros: mutable, good capabilities
    - cons: still foreign to many R users
    
In any case, I'll need to figure out how to make expressions be defaults. E.g. the default for logWc_hat should be mean(logW)

- For this, just use quote() and eval(), as stipulated in Hadley's book (under NSE)

**Attempt 1**: 

- Set defaults as options
    - Doing this in 
- Make generating function that takes bamdata argument, returns list of defaults
- Modify defaults in higher-level function after calling default generator

